name: "JFrog Python Example"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
  security-events: write

env:
  BUILD_NAME: "JFrog-Scan-Example-Build"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      # Setup JFrog CLI using OIDC
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: kamalkn24/sws-jf-example-python-test2@github

      # Configure pip to resolve from Artifactory
      - name: Configure pip
        run: |
          jf pip-config \
            --repo-resolve=sws-jf-example-python-remote \
            --server-id-resolve=setup-jfrog-cli-server

      # Install dependencies
      - name: Install Python Dependencies
        run: |
          jf pip install --upgrade pip setuptools wheel build
          jf pip install -r requirements.txt \
            --build-name $BUILD_NAME \
            --build-number $BUILD_NUMBER \
            --project=jf-example

      # Build artifact
      - name: Build artifact
        run: |
          python -m build

      # Upload artifacts and build info
      - name: Upload artifact and build info
        run: |
          jf rt bce $BUILD_NAME $BUILD_NUMBER --project=jf-example

          jf rt upload "dist/*" "sws-jf-example-python-local" \
            --build-name $BUILD_NAME \
            --build-number $BUILD_NUMBER \
            --project=jf-example

          jf rt bad $BUILD_NAME $BUILD_NUMBER requirements.txt --project=jf-example

          jf rt bp $BUILD_NAME $BUILD_NUMBER --project=jf-example

      # Xray build scan
      - name: Run Xray scan
        run: |
          jf build-scan $BUILD_NAME $BUILD_NUMBER \
            --fail=true \
            --format=sarif \
            --project=jf-example > jfrog_scan_results.sarif

      # Dependency audit
      - name: Xray dependency audit
        run: |
          jf audit --format=sarif > jfrog_audit_results.sarif

      # Upload SARIF results to GitHub Security tab
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: jfrog_scan_results.sarif
